# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 902f289ee3749d7bb96f8fcbcc506aae1382d8c220850ff299328642829eee7a81d95e991b7652f995815cf6f053d0eb3973d42b5541b7586074cfbf353ee912

test:
  secret_key_base: b5e2ac066f19493278f59ae2e3414fbbafd085cb521e4f1714d5cd05fdbaaebdf9daf3bae32cf829401c316abbf15945d7a5254259c5b3c8f809caf6eb3e910f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
